const express = require('express');
const FcfsRouter = express.Router();
const { CalculateGanttChartMethod, CalculateCTProperty, CalculateTTProperty, CalculateWTProperty, CalculateRTProperty, CalculateProperty } = require("../controller/fcfsController");
FcfsRouter.route("/ganttChart").post(CalculateGanttChartMethod);
FcfsRouter.route("/completionTime").post(CalculateCTProperty);
FcfsRouter.route("/turnaroundTime").post(CalculateTTProperty);
FcfsRouter.route("/waitingTime").post(CalculateWTProperty);
FcfsRouter.route("/responseTime").post(CalculateRTProperty);
FcfsRouter.route("/property").post(CalculateProperty);
module.exports = FcfsRouter;
